### ISSUE TITLE
Test support for non-ascii characters

### ISSUE THREAD

**Issue by esgibter** [esgibter/fandomstats#18]
Mentioned by @destinationtoast in #13: 

Test fetching canonical tags:

```
Les Misérables - All Media Types
20世紀少年 | 20th Century Boys (Manga)
```

**Comment by annathecrow** [comment]
Yep, [https://annathecrow.tumblr.com/post/162699957162/hi-sorry-i-didnt-feel-comfortable-emailing-about](this is broken). :-/ 

Tag to test for: '방탄소년단 | Bangtan Boys | BTS'

**Comment by destinationtoast** [comment]
Oh, dammit!  I have tried to debug this several times and just don't know
how to fix it. Been tearing my hair out a bit. :(

**Comment by annathecrow** [comment]
I found it: #66 It was badly set up request parser.

But ugh, python _sucks_ at unicode - it's always such a mess.
