### ISSUE TITLE
Error Handling for stats

### ISSUE THREAD

**Issue by esgibter** [esgibter/fandomstats#19]
Once flask restful is in, this will be a lot easier. Error case to add:
* 400 (Bad Request) for a malformed URL (when a call to AO3 results in a 404)
* ~~400 (Bad Request) for any incorrectly formatted input value. e.g. other_tag_ids must be a number, other_tag_names must be a string~~

As I come across more I'll add them to this ticket.

**Comment by esgibter** [comment]
Example of a URL which is a 404 on ao3 and currently returns a 500 in our app:
```
/api/v1.0/stats?tag_id=Harry+j&bookmarks_count=3&complete=0&character_ids=1589&character_ids=1048&sort_direction=desc&page=2
```

Should return a 400 in our app instead

**Comment by annathecrow** [comment]
This is done ([as seen here](https://github.com/esgibter/fandomstats/blob/4b170817b3ce44b017c50f84c353bdf6633e2e15/src/application/api/models.py#L74-L102)). I had a bit of perfectionist fun picking the right error codes (I was _this_ close to using [418 I am a Teapot](https://httpstatuses.com/418) at one point), so we're returning:

* 501 Not Implemented (when AO3 redirects to canonical tag)
* 400 Bad Request (malformed url or no results)
* 500 Internal Server Error (when something borks on our side)

It could stand refactoring into something less messy, but it's good enough for now, imho.
