### ISSUE TITLE
Don't show Hover when someone uses wrong url

### ISSUE THREAD

**Issue by annathecrow** [esgibter/fandomstats#37]
I've been flailing around, trying to remember the right url for the api, and I kept getting this. Definitely not supposed to happen. What the hell *is* that thing anyway? I do think Flask returns 404 as it should, but the visitor gets Hover.

**Comment by annathecrow** [comment]
okay, this keeps happening. Today I've got Hover twice, and when I tried them later, I got the proper JSON result. I don't know what's happening here, and google isn't helping. Is this a Flask bug? Is something wrong with our app engine setup?

**Comment by esgibter** [comment]
Huh weird. Can you add more examples here? E.g. add the URL you see the hover page vs the json page. 

I think there's definitely an issue with the malformed url returning a hover page instead of being caught with a flask http error.

**Comment by destinationtoast** [comment]
I've had this happen lately, too -- will try to record examples, but
they're well-formed URLs that sometimes yield Hover instead of results!

**Comment by esgibter** [comment]
Hm I could add logging as the first step. Might be a google apps engine thing.

**Comment by esgibter** [comment]
Ok I deployed a first fix for two potential error cases. if you keep seeing this let me know how you reproduced!

**Comment by destinationtoast** [comment]
I got the hover error again, this time for the following URLs:
http://fandomstats.com
http://fandomstats.com/index.html
http://fandomstats.com/api/v1.0/stats?tag_id=F/F

**Comment by annathecrow** [comment]
today I got a Hover on this url: http://fandomstats.com/api/v1.0/stats?tag_id=F/F&tag_id=Carmilla
It it the same Hover as usual? It feels a little different, but I don't have any old screenshots.
![2015-06-20_170733](https://cloud.githubusercontent.com/assets/4406275/8267837/32439a28-176f-11e5-9506-e56ad71d5011.png)

**Comment by annathecrow** [comment]
Today I got a Hover on http://fandomstats.com. I had to reload several times before I got to the page. :(

According to the App Engine logs:

> This request caused a new process to be started for your application, and thus caused your application code to be loaded for the first time. This request may thus take longer and use more CPU than a typical request for your application.

Is it possible that Hover does some automatic check on the IP? I can't find anything about it. We need to either disable that (if it's happening) or get App Engine to keep the process running. Otherwise people are going to get Hover pages. :[

**Comment by annathecrow** [comment]
Fixed.

We forgot to remove the default A-records that Hover has in the DNS settings. There are two ("@" and "*"), both pointing at "64.98.145.30" - the problematic Hover server from my last comment. 

I can't believe I didn't notice this sooner.
