### ISSUE TITLE
Graphs: turn ratings into (pie) charts

### ISSUE THREAD

**Issue by esgibter** [esgibter/fandomstats#8]

**Comment by annathecrow** [comment]
Issue hijack! This is now a general "make graphs" issue.

Quoting myself from [here](https://github.com/esgibter/fandomstats/issues/21#issuecomment-63170906):

> 
> graphs:
> total number of fanworks - integer (possibly also percent of AO3 total)
> ratings - pie chart
> relationship categories - bar chart
> fandoms - bar chart
> characters - bar chart
> relationships - bar chart
> additional tags - bar chart

**Comment by annathecrow** [comment]
Done!
