### ISSUE TITLE
Fix quotes around tags or instructions on searching?

### ISSUE THREAD

**Issue by destinationtoast** [esgibter/fandomstats#87]
On the main page, it gives a couple examples of how to search, like 'Harry Potter', and it's ambiguous whether you're supposed to use quotes around the tag when you do the search.  I've had people write to me to say it's broken because they used single or double quotes and it failed.  

I'm guessing we can't change it to accept either single or double quotes in the search box, because they can both appear within tags?  Maybe we should change the instructions in the search box to clarify that quotes around tags aren't allowed?

**Comment by annathecrow** [comment]
Hypothetically, it should be possible to trim single/double quotes... but you're right, we should just change the wording. Actually, I have read recently that using placeholder attribute to explain form fields is discouraged for accessibility reasons. So I'd say that the best solution would be to move the text out and use either *italics* or `code`, e.g.:

> Enter one or more comma-separated tags, e.g. *Harry Potter* or *Star Wars, fluff*

> Enter one or more comma-separated tags, e.g. `Harry Potter` or `Star Wars, fluff`.
